---
title: "R Notebook"
output: html_notebook
---

```{r}
meta_colors <- list(
  "cluster" = c( 
    "1" = "#1f78b4", 
    "2" = "#08519c",
    "3" = "#b2df8a", 
    "4" = "#33a02c",
    "5" = "#005a32",
    "6" = "#fb9a99", 
    "7" = "#e31a1c",
    "8" = "#fdbf6f",
    "9" = "#ff7f00"
    
  ),
  "cluster.v2" = c( 
    "1" = "#1f78b4", 
    "2" = "#08519c",
    "3" = "#b2df8a", 
    "4" = "#33a02c",
    "5" = "#005a32",
    "6" = "#fb9a99", 
    "7" = "#e31a1c",
    "8" = "#fdbf6f",
    "9" = "#ff7f00"
  )
)
```

```{r}
library(R.matlab)
folder <- "../04-25-2021-Extract_all_data_per_cells_wo_Survivin"
Data <- readMat(file.path(folder, "DMSO_Cluster_Distribution_wo_dual_colors.mat"))

Cellnames <- unlist(Data[[1]])
Cluster.distribution <- Data[[2]]

Nums.precell <- rowSums(Cluster.distribution)

Cluster.distr.prop <- apply(Cluster.distribution, 2, function(x) x/Nums.precell)

temp.index <- which(Nums.precell >= 10)
Cluster.distr.prop <- Cluster.distr.prop[temp.index, ]
Cluster.distribution <- Cluster.distribution[temp.index, ]
Cellnames <- Cellnames[temp.index]
```


```{r}
#Create a folder to save the results.
saved.dir <- './Clustering_Analysis_K_10_Representive_correlation'
if (!dir.exists(saved.dir)){
  dir.create((saved.dir))
}
```

Proportion Plot per each cluster
```{r}
library(boot)
library(ggplot2)
library(reshape2)
library(tidyverse)
library(ggrepel)
library(philentropy)
mean.fun <- function(data, idx) 
{ 
  df <- data[idx] 
  
  # Find the spearman correlation between  
  # the 3rd and 4th columns of dataset 
  c(mean(df)) 
} 

K = 10
cluster <- readRDS(file.path('./', paste0('cluster_K_', toString(K), '_ordered.RDS')))

for(index in 1 : max(cluster)){
  temp.index <- which(cluster == index)
  temp.prop <- Cluster.distr.prop[temp.index, ]
  temp.name <- Cellnames[temp.index]
  rownames(temp.prop) <- temp.name
  temp.means <- round(colMeans(temp.prop), 2)
  

  df <- data.frame(mean.value = temp.means) 
  
  df$Clusters <- c("1", "2", "3", "4", "5", "6")
  
  df <- cbind(df, t(temp.prop))
  

  dist <- distance(t(df[, c(1, 3: dim(df)[2])]), method = "euclidean")
  dist_wMeanValue <- dist[1, 2:dim(dist)[2]]
  dist.df <- data.frame(dist = dist_wMeanValue, name = colnames(df)[3: dim(df)[2]])
  ggplot(dist.df, aes(x = name, y = dist)) +
    geom_point(size = 1) +
    theme_classic(base_size = 8) +
    theme(
      panel.grid = element_blank(),
      legend.position = "none",
      plot.title = element_text(color="black", face = "italic"),
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    labs(y = "Dist between each cell and Mean", title = toString(index))
  
    ggsave(file.path(saved.dir, paste0("Dist_scCluster_", toString(index), ".png")), width = 6, height = 3, units = "in", dpi = 300)

  df.data <- melt(df)
  # Most basic error bar
  plt <- ggplot(df.data, aes(x=Clusters, y=value, group=variable, color = variable), fill=meta_colors$cluster[[index]]) +
    geom_line() +
    geom_point(size=1) +
    #geom_text_repel(aes(label = variable), color = "black", size = 1) +
    theme_classic(base_size = 8) +
    theme(
      panel.grid = element_blank(),
      legend.position = "none",
      plot.title = element_text(color="black", face = "italic")
      ) +
    labs(y = "Average Proportion (%)")
  plt
  ggsave(file.path(saved.dir, paste0("Plot_scCluster_", toString(index), ".png")), width = 3, height = 3, units = "in", dpi = 300)
  saveRDS(df, file.path(saved.dir, paste0("Cluster_", toString(index), ".Rds")))
}
```



