---
title: "R Notebook"
output: html_notebook
---

```{r}
meta_colors <- list(
  "cluster" = c( 
    "1" = "#1f78b4", 
    "2" = "#08519c",
    "3" = "#b2df8a", 
    "4" = "#33a02c",
    "5" = "#005a32",
    "6" = "#fb9a99", 
    "7" = "#e31a1c",
    "8" = "#fdbf6f",
    "9" = "#ff7f00"
    
  ),
  "cluster.v2" = c( 
    "1" = "#1f78b4", 
    "2" = "#08519c",
    "3" = "#b2df8a", 
    "4" = "#33a02c",
    "5" = "#005a32",
    "6" = "#fb9a99", 
    "7" = "#e31a1c",
    "8" = "#fdbf6f",
    "9" = "#ff7f00"
  )
)
```


```{r}
library(ggplot2)
K = 12
saved.dir <- './Clustering_Analysis'

cluster <- readRDS(file.path(saved.dir, paste0('cluster_K_', toString(K), '.RDS')))
cluster <- as.integer(cluster)
cluster.order <- cluster
cluster.order[which(cluster == 3)] <- 1
cluster.order[which(cluster == 9)] <- 2
cluster.order[which(cluster == 1)] <- 3
cluster.order[which(cluster == 5)] <- 4
cluster.order[which(cluster == 2)] <- 5
cluster.order[which(cluster == 7)] <- 6
cluster.order[which(cluster == 4)] <- 7
cluster.order[which(cluster == 6)] <- 8
cluster.order[which(cluster == 8)] <- 9
cluster <- cluster.order
saveRDS(cluster, file.path('.', 'cluster_K_12_ordered.RDS'))

folder <- "../Single_cell_clustering_woSurvivin/PCA_Analysis"
PCA.Umap.result <- readRDS(file.path(folder, 'PCA.Umap.results.RDS'))

#Create a folder to save the results.
saved.dir <- './Clustering_Analysis_K_12'


df.plot <- PCA.Umap.result
df.plot$cluster <- as.factor(cluster)
options(repr.plot.height = 3, repr.plot.width = 3)
ggplot(data = df.plot[sample(nrow(df.plot)),]) +
  geom_point(
    mapping = aes_string(x = "UMAP1", y = "UMAP2", fill = "cluster", color = "cluster"),
    size = 2, stroke = 0.00001, shape = 21) +
  labs(x = "UMAP1",y = "UMAP2") +
  scale_color_manual(values = meta_colors$cluster) +
  scale_fill_manual(values = meta_colors$cluster) +
  theme_classic(base_size = 8) +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    legend.position = "none",
    plot.title = element_text(color="black", size=8, face = "italic")
  )
filename <- 'UMAP_K_12_v3.png'
ggsave(file = file.path(saved.dir, filename), width = 2, height = 2, dpi = 300)

#PDF
filename <- 'UMAP_K_12_v3.pdf'
ggsave(file = file.path(saved.dir, filename), width = 2, height = 2, dpi = 300)
```

